### ISSUE TITLE
Export MotionFade back to Motion3Json

### ISSUE THREAD

**Issue by gradualcolors** [Perfare/UnityLive2DExtractor#1]
Hello, I'm not sure where this question would go between your UnityLive2D Extractor or AssetStudio. I have some issues with exporting out some motion3.json files that have been converted to .fade files. They are all MonoBehaviour scripts with Animation clips. Looking at it in AssetStudio, the .fade files contains the parameters and keyframe data.

Is it possible if you could look at this if it can be returned back to its json file? Thank you very much.
[enstarsl2dmotions.zip](https://github.com/Perfare/UnityLive2DExtractor/files/4726414/enstarsl2dmotions.zip)

**Comment by Perfare** [comment]
Thanks for your feedback, I will research how to restore it.

**Comment by gradualcolors** [comment]
Thank you very much!

**Comment by gradualcolors** [comment]
Hi! I solved the issue. It seems like the motions were separate but the Animator was still on each of the Live2D models. I modified your program a bit to point the animationclips to the motion file so it could load it in. Thank you so much for your extractor.

**Comment by Perfare** [comment]
I'm glad to hear that you have solved this problem, would you consider sending pr or sharing your code?

**Comment by gradualcolors** [comment]
Sure I'll share what I did. I created a second AssetsManager variable to load the animation clips from the separate file. I kept the motion file path static since it was to be used for extracting multiple models from Ensemble Stars. The motionfade files were irrelevant. It's used for blending fade, so it contained some of the motion3json data which was confusing. What mattered was the animation clips. 

```
if (args.Length == 0)
                return;
foreach (var arg in args)
           {
              if (!File.Exists(arg))
                   continue;

 var path = Path.GetFullPath(arg);
 var assetsManager = new AssetsManager();
                assetsManager.LoadFiles(path);
                if (assetsManager.assetsFileList.Count == 0)
                {
                    continue;
                }
var assets = assetsManager.assetsFileList[0].Objects.Values.ToList();

/*Second AssetManager for Motions */

var motion_path = "\\_motions.unity3d";           //path to the the motion file
var motionManager = new AssetsManager();
            motionManager.LoadFiles(motion_path);
            if (motionManager.assetsFileList.Count == 0)
            {
                  continue;
            }
var mmotions = motionManager.assetsFileList[0].Objects.Values.ToList();

...

var motions = new List<string>();
var animator = (Animator)assets.First(x => x is Animator);
var animations = mmotions.OfType<AnimationClip>().ToArray();  //changed "assets" to "mmotions" to load animation clips from motionManager
```
