### ISSUE TITLE
Splitted motion files

### ISSUE THREAD

**Issue by sinyo1015** [Perfare/UnityLive2DExtractor#2]
Hi, I have some problems. Similar like #1 , but the motions file are likely scattered / splitted over other file. For example `xxxx.unity3d has CubismDrawable#1` and `xxx2.unity3d has CubismDrawable#2` and so on (Based on my prediction, not check all files btw.)

Here's I got from `AssetStudio`
- `CubismAutoEyeBlinkInput#n`,
- `CubismDrawable#n`,
- `CubismEyeBlinkController#n`,
- `CubismHarmonicMotionController#n`,
- `CubismHarmonicMotionParameter#n`,
- `CubismLookController#n`,
- `CubismModel#n`,
- `CubismMouthController#n`,
- `CubismParameter#n`,
- `CubismPart#n`,
- `CubismPartInspector#n`,
- `CubismPhysicsController#n`,
- `CubismRenderController#n`,
- `CubismRenderer#n`,
- `...etc`

They all were splitted in different `.unity3d` file and the type is `MonoBehaviour`, _this cause live2d models are not having any `.motion3.json` at all._ 

I'm using `AssetStudio` to lookup any model linked file and using `UnityLive2DExtractor` to extract from file. Any help or tricks would be appreciated, and thanks for providing awesome tool for extract live2d model.

**Comment by Perfare** [comment]
Can you upload files to me? This will make it easier for me to implement and test.

**Comment by sinyo1015** [comment]
here you go https://1drv.ms/u/s!AjR9QK0sGQJKiFXP7PXEzlJOBV3D?e=qVfdJp

**Comment by sinyo1015** [comment]
I've found the problem. Turns out, the proper motion files are in different container. I've looked out for entire game assets and found it out.

**Comment by Perfare** [comment]
OK, but I have perfected the program, now drag into the entire folder, it will automatically recognize and export.
