### ISSUE TITLE
ERROR:不输出任何输出后的文件，显示Loading后程序结束

### ISSUE THREAD

**Issue by EUEUE39** [Perfare/UnityLive2DExtractor#9]
![image](https://user-images.githubusercontent.com/40299416/140311835-d57e456e-b2a8-4ae3-9a2b-e74e1f84b810.png)

https://drive.google.com/file/d/17Z7FTLJL6lcpRnMnTgjd0IPpTbNuAr6B/view?usp=sharing

使用版本是1.0.3

**Comment by Perfare** [comment]
已更新

**Comment by EUEUE39** [comment]
但是仍然不能导出motion？

**Comment by Perfare** [comment]
如果开发者不把moc和动作文件放在一个文件夹下的话，程序很难判断一个模型能匹配哪些动作文件，所以除非你自己修改代码，目前是不会导出不在一个目录下的动作的。
